# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Schema'),
        ),
    ]
