# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-08 08:26
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20181123_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='data',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
