# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-14 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20190308_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='name',
            field=models.CharField(default=shortuuid.main.uuid, max_length=100, unique=True),
        ),
    ]
